package cl.mochasoft.gui;

import cl.mochasoft.model.CompaniaEngine;
import cl.mochasoft.model.CompaniaPlataforma;
import cl.mochasoft.model.Data;
import cl.mochasoft.model.Juego;
import cl.mochasoft.model.Staff;
import cl.mochasoft.model.StaffDespedido;
import cl.mochasoft.model.TMJuegos;
import cl.mochasoft.model.TMStaff;
import cl.mochasoft.model.TMStaffDespedido;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge A
 */
public class App extends javax.swing.JFrame {

    Data dat;

    public App() {
        try {
            dat = new Data();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        setLocationRelativeTo(null);
        setTitle("MochaSoft v0.1b - Versión Beta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameBorrar = new javax.swing.JFrame();
        pnlBorrarStaff = new javax.swing.JPanel();
        lblDespedirStaff = new javax.swing.JLabel();
        txtNombreStaffDespedido = new javax.swing.JTextField();
        btnAceptarDespedirStaff = new javax.swing.JButton();
        frameEstadisticas = new javax.swing.JFrame();
        tpEstadisticas = new javax.swing.JTabbedPane();
        pnlVerJuegos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabJuegos = new javax.swing.JTable();
        pnlVerJuegosPorAnio = new javax.swing.JPanel();
        lblJuegosPorAnio = new javax.swing.JLabel();
        txtVerJuegosPorAnio = new javax.swing.JTextField();
        btnVerJuegosPorAnio = new javax.swing.JButton();
        lblResultadosPorAnio = new javax.swing.JLabel();
        txtVerResultadosJuegosAnio = new javax.swing.JTextField();
        pnlVerStaff = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabStaff = new javax.swing.JTable();
        pnlVerStaffDespedido = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabStaffDespedido = new javax.swing.JTable();
        tbpPanel = new javax.swing.JTabbedPane();
        pnlRegistroJuego = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblPlataforma = new javax.swing.JLabel();
        lblEngine = new javax.swing.JLabel();
        lblUnidadesVendidas = new javax.swing.JLabel();
        lblVersionJuego = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtVersion = new javax.swing.JTextField();
        btnAceptarRegistroJuego = new javax.swing.JButton();
        cboGenero = new javax.swing.JComboBox<>();
        cboPlataforma = new javax.swing.JComboBox<>();
        cboEngine = new javax.swing.JComboBox<>();
        spnUnidades = new javax.swing.JSpinner();
        pnlRegistroGenero = new javax.swing.JPanel();
        lblNombreGenero = new javax.swing.JLabel();
        txtNombreGenero = new javax.swing.JTextField();
        btnRegistroGenero = new javax.swing.JButton();
        pnlRegistroPlataforma = new javax.swing.JPanel();
        lblNombrePlataforma = new javax.swing.JLabel();
        txtNombrePlataforma = new javax.swing.JTextField();
        lblCompaniaPlataforma = new javax.swing.JLabel();
        txtCompaniaPlataforma = new javax.swing.JTextField();
        btnRegistrarPlataforma = new javax.swing.JButton();
        btnBuscarCompPlat = new javax.swing.JButton();
        lblPlatEncontrado = new javax.swing.JLabel();
        pnlRegistroEngine = new javax.swing.JPanel();
        lblNombreEngine = new javax.swing.JLabel();
        lblCompaniaEngine = new javax.swing.JLabel();
        txtNombreEngine = new javax.swing.JTextField();
        txtCompaniaEngine = new javax.swing.JTextField();
        btnRegistrarEngine = new javax.swing.JButton();
        lblEngineEncontrado = new javax.swing.JLabel();
        btnBuscarCompEn = new javax.swing.JButton();
        pnlRegistroStaff = new javax.swing.JPanel();
        lblNombreStaff = new javax.swing.JLabel();
        txtNombreStaff = new javax.swing.JTextField();
        btnRegistrarStaff = new javax.swing.JButton();
        mebApp = new javax.swing.JMenuBar();
        menArchivo = new javax.swing.JMenu();
        meiBorrar = new javax.swing.JMenuItem();
        meiEstadisticas = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        meiAcercaDe = new javax.swing.JMenuItem();

        pnlBorrarStaff.setBorder(javax.swing.BorderFactory.createTitledBorder("Despedir Staff"));

        lblDespedirStaff.setText("Nombre:");

        btnAceptarDespedirStaff.setText("Aceptar");

        javax.swing.GroupLayout pnlBorrarStaffLayout = new javax.swing.GroupLayout(pnlBorrarStaff);
        pnlBorrarStaff.setLayout(pnlBorrarStaffLayout);
        pnlBorrarStaffLayout.setHorizontalGroup(
            pnlBorrarStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrarStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDespedirStaff)
                .addGap(18, 18, 18)
                .addComponent(txtNombreStaffDespedido, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptarDespedirStaff)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pnlBorrarStaffLayout.setVerticalGroup(
            pnlBorrarStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrarStaffLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlBorrarStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDespedirStaff)
                    .addComponent(txtNombreStaffDespedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarDespedirStaff))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameBorrarLayout = new javax.swing.GroupLayout(frameBorrar.getContentPane());
        frameBorrar.getContentPane().setLayout(frameBorrarLayout);
        frameBorrarLayout.setHorizontalGroup(
            frameBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBorrarStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameBorrarLayout.setVerticalGroup(
            frameBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBorrarStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabJuegos);

        javax.swing.GroupLayout pnlVerJuegosLayout = new javax.swing.GroupLayout(pnlVerJuegos);
        pnlVerJuegos.setLayout(pnlVerJuegosLayout);
        pnlVerJuegosLayout.setHorizontalGroup(
            pnlVerJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerJuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVerJuegosLayout.setVerticalGroup(
            pnlVerJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerJuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpEstadisticas.addTab("Ver Juegos", pnlVerJuegos);

        lblJuegosPorAnio.setText("Ingrese Año:");

        btnVerJuegosPorAnio.setText("Aceptar");
        btnVerJuegosPorAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerJuegosPorAnioActionPerformed(evt);
            }
        });

        lblResultadosPorAnio.setText("Resultados:");

        txtVerResultadosJuegosAnio.setEditable(false);

        javax.swing.GroupLayout pnlVerJuegosPorAnioLayout = new javax.swing.GroupLayout(pnlVerJuegosPorAnio);
        pnlVerJuegosPorAnio.setLayout(pnlVerJuegosPorAnioLayout);
        pnlVerJuegosPorAnioLayout.setHorizontalGroup(
            pnlVerJuegosPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerJuegosPorAnioLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(pnlVerJuegosPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVerJuegosPorAnioLayout.createSequentialGroup()
                        .addComponent(lblJuegosPorAnio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVerJuegosPorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVerJuegosPorAnioLayout.createSequentialGroup()
                        .addComponent(lblResultadosPorAnio)
                        .addGap(32, 32, 32)
                        .addComponent(txtVerResultadosJuegosAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnVerJuegosPorAnio)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlVerJuegosPorAnioLayout.setVerticalGroup(
            pnlVerJuegosPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerJuegosPorAnioLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnlVerJuegosPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJuegosPorAnio)
                    .addComponent(txtVerJuegosPorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerJuegosPorAnio))
                .addGap(24, 24, 24)
                .addGroup(pnlVerJuegosPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVerResultadosJuegosAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadosPorAnio))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        tpEstadisticas.addTab("Ver Juegos por Año", pnlVerJuegosPorAnio);

        tabStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabStaff);

        javax.swing.GroupLayout pnlVerStaffLayout = new javax.swing.GroupLayout(pnlVerStaff);
        pnlVerStaff.setLayout(pnlVerStaffLayout);
        pnlVerStaffLayout.setHorizontalGroup(
            pnlVerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVerStaffLayout.setVerticalGroup(
            pnlVerStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpEstadisticas.addTab("Ver Staff", pnlVerStaff);

        tabStaffDespedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabStaffDespedido);

        javax.swing.GroupLayout pnlVerStaffDespedidoLayout = new javax.swing.GroupLayout(pnlVerStaffDespedido);
        pnlVerStaffDespedido.setLayout(pnlVerStaffDespedidoLayout);
        pnlVerStaffDespedidoLayout.setHorizontalGroup(
            pnlVerStaffDespedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerStaffDespedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVerStaffDespedidoLayout.setVerticalGroup(
            pnlVerStaffDespedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerStaffDespedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpEstadisticas.addTab("Ver Staff Despedido", pnlVerStaffDespedido);

        javax.swing.GroupLayout frameEstadisticasLayout = new javax.swing.GroupLayout(frameEstadisticas.getContentPane());
        frameEstadisticas.getContentPane().setLayout(frameEstadisticasLayout);
        frameEstadisticasLayout.setHorizontalGroup(
            frameEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpEstadisticas)
                .addContainerGap())
        );
        frameEstadisticasLayout.setVerticalGroup(
            frameEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEstadisticasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tpEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRegistroJuego.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo.setText("Título:");

        lblGenero.setText("Género:");

        lblAnio.setText("Año:");

        lblPlataforma.setText("Plataforma:");

        lblEngine.setText("Engine:");

        lblUnidadesVendidas.setText("Unidades Vendidas:");

        lblVersionJuego.setText("Version Juego:");

        btnAceptarRegistroJuego.setText("Aceptar");
        btnAceptarRegistroJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRegistroJuegoActionPerformed(evt);
            }
        });

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboEngine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlRegistroJuegoLayout = new javax.swing.GroupLayout(pnlRegistroJuego);
        pnlRegistroJuego.setLayout(pnlRegistroJuegoLayout);
        pnlRegistroJuegoLayout.setHorizontalGroup(
            pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistroJuegoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptarRegistroJuego))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroJuegoLayout.createSequentialGroup()
                        .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenero)
                            .addComponent(lblTitulo)
                            .addComponent(lblAnio))
                        .addGap(73, 73, 73)
                        .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboGenero, javax.swing.GroupLayout.Alignment.TRAILING, 0, 405, Short.MAX_VALUE)
                            .addComponent(txtAnio)
                            .addComponent(txtTitulo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroJuegoLayout.createSequentialGroup()
                        .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlataforma)
                            .addComponent(lblEngine))
                        .addGap(56, 56, 56)
                        .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboEngine, 0, 369, Short.MAX_VALUE)
                            .addComponent(cboPlataforma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroJuegoLayout.createSequentialGroup()
                        .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUnidadesVendidas)
                            .addComponent(lblVersionJuego))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVersion)
                            .addComponent(spnUnidades))))
                .addContainerGap())
        );
        pnlRegistroJuegoLayout.setVerticalGroup(
            pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroJuegoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlataforma)
                    .addComponent(cboPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEngine)
                    .addComponent(cboEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadesVendidas)
                    .addComponent(spnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVersionJuego)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptarRegistroJuego)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpPanel.addTab("Registro Juegos", pnlRegistroJuego);

        pnlRegistroGenero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreGenero.setText("Nombre:");

        btnRegistroGenero.setText("Aceptar");
        btnRegistroGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroGeneroLayout = new javax.swing.GroupLayout(pnlRegistroGenero);
        pnlRegistroGenero.setLayout(pnlRegistroGeneroLayout);
        pnlRegistroGeneroLayout.setHorizontalGroup(
            pnlRegistroGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroGeneroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistroGenero)
                    .addGroup(pnlRegistroGeneroLayout.createSequentialGroup()
                        .addComponent(lblNombreGenero)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        pnlRegistroGeneroLayout.setVerticalGroup(
            pnlRegistroGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroGeneroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlRegistroGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreGenero)
                    .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistroGenero)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        tbpPanel.addTab("Registro Género", pnlRegistroGenero);

        pnlRegistroPlataforma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombrePlataforma.setText("Nombre:");

        lblCompaniaPlataforma.setText("Compañia:");

        btnRegistrarPlataforma.setText("Aceptar");
        btnRegistrarPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPlataformaActionPerformed(evt);
            }
        });

        btnBuscarCompPlat.setText("Buscar");
        btnBuscarCompPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompPlatActionPerformed(evt);
            }
        });

        lblPlatEncontrado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnlRegistroPlataformaLayout = new javax.swing.GroupLayout(pnlRegistroPlataforma);
        pnlRegistroPlataforma.setLayout(pnlRegistroPlataformaLayout);
        pnlRegistroPlataformaLayout.setHorizontalGroup(
            pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroPlataformaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroPlataformaLayout.createSequentialGroup()
                        .addGroup(pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarPlataforma)
                            .addGroup(pnlRegistroPlataformaLayout.createSequentialGroup()
                                .addGroup(pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroPlataformaLayout.createSequentialGroup()
                                        .addComponent(lblNombrePlataforma)
                                        .addGap(29, 29, 29))
                                    .addGroup(pnlRegistroPlataformaLayout.createSequentialGroup()
                                        .addComponent(lblCompaniaPlataforma)
                                        .addGap(15, 15, 15)))
                                .addGroup(pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCompaniaPlataforma)
                                    .addComponent(txtNombrePlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCompPlat))
                    .addComponent(lblPlatEncontrado))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlRegistroPlataformaLayout.setVerticalGroup(
            pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroPlataformaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePlataforma)
                    .addComponent(txtNombrePlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistroPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompaniaPlataforma)
                    .addComponent(txtCompaniaPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCompPlat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarPlataforma)
                .addGap(18, 18, 18)
                .addComponent(lblPlatEncontrado)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        tbpPanel.addTab("Registro Plataforma", pnlRegistroPlataforma);

        pnlRegistroEngine.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreEngine.setText("Nombre:");

        lblCompaniaEngine.setText("Compañia:");

        btnRegistrarEngine.setText("Aceptar");
        btnRegistrarEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEngineActionPerformed(evt);
            }
        });

        lblEngineEncontrado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnBuscarCompEn.setText("Buscar");
        btnBuscarCompEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompEnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroEngineLayout = new javax.swing.GroupLayout(pnlRegistroEngine);
        pnlRegistroEngine.setLayout(pnlRegistroEngineLayout);
        pnlRegistroEngineLayout.setHorizontalGroup(
            pnlRegistroEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroEngineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroEngineLayout.createSequentialGroup()
                        .addGroup(pnlRegistroEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroEngineLayout.createSequentialGroup()
                                .addComponent(lblNombreEngine)
                                .addGap(28, 28, 28)
                                .addComponent(txtNombreEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroEngineLayout.createSequentialGroup()
                                .addComponent(lblCompaniaEngine)
                                .addGap(18, 18, 18)
                                .addComponent(txtCompaniaEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRegistrarEngine, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCompEn))
                    .addComponent(lblEngineEncontrado))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        pnlRegistroEngineLayout.setVerticalGroup(
            pnlRegistroEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroEngineLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlRegistroEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEngine)
                    .addComponent(txtNombreEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompaniaEngine)
                    .addComponent(txtCompaniaEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCompEn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarEngine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEngineEncontrado)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        tbpPanel.addTab("Registro Engine", pnlRegistroEngine);

        pnlRegistroStaff.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreStaff.setText("Nombre:");

        btnRegistrarStaff.setText("Aceptar");
        btnRegistrarStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroStaffLayout = new javax.swing.GroupLayout(pnlRegistroStaff);
        pnlRegistroStaff.setLayout(pnlRegistroStaffLayout);
        pnlRegistroStaffLayout.setHorizontalGroup(
            pnlRegistroStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrarStaff)
                    .addGroup(pnlRegistroStaffLayout.createSequentialGroup()
                        .addComponent(lblNombreStaff)
                        .addGap(28, 28, 28)
                        .addComponent(txtNombreStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        pnlRegistroStaffLayout.setVerticalGroup(
            pnlRegistroStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroStaffLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlRegistroStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreStaff)
                    .addComponent(txtNombreStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarStaff)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        tbpPanel.addTab("Registro Staff", pnlRegistroStaff);

        menArchivo.setText("Archivo");

        meiBorrar.setText("Borrar");
        meiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiBorrarActionPerformed(evt);
            }
        });
        menArchivo.add(meiBorrar);

        meiEstadisticas.setText("Estadísticas");
        meiEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiEstadisticasActionPerformed(evt);
            }
        });
        menArchivo.add(meiEstadisticas);

        mebApp.add(menArchivo);

        menAyuda.setText("Ayuda");

        meiAcercaDe.setText("Acerca de...");
        meiAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiAcercaDeActionPerformed(evt);
            }
        });
        menAyuda.add(meiAcercaDe);

        mebApp.add(menAyuda);

        setJMenuBar(mebApp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiBorrarActionPerformed
        frameBorrar.setVisible(true);
        frameBorrar.setBounds(550, 100, 500, 500);
        frameBorrar.setLocationRelativeTo(null);
        frameBorrar.setTitle("Borrar");
    }//GEN-LAST:event_meiBorrarActionPerformed

    private void meiEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiEstadisticasActionPerformed
        frameEstadisticas.setVisible(true);
        frameEstadisticas.setBounds(550, 100, 500, 500);
        frameEstadisticas.setLocationRelativeTo(null);
        frameEstadisticas.setTitle("Estadísticas");
        cargarTblJuegos();
        cargarTblStaff();
        cargarTblStaffDespedido();
    }//GEN-LAST:event_meiEstadisticasActionPerformed

    private void meiAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiAcercaDeActionPerformed
        playSound();
        String titVentana = "Información";
        String vntMensaje = "Software Creado por Jorge Anjel - Javier Vergara - 16/08/2018.";

        int tipoa = JOptionPane.INFORMATION_MESSAGE;

        JOptionPane.showMessageDialog(this, vntMensaje, titVentana, tipoa);
    }//GEN-LAST:event_meiAcercaDeActionPerformed

    private void btnVerJuegosPorAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerJuegosPorAnioActionPerformed

        String anio = txtVerJuegosPorAnio.getText();

        try {
            int reslut = dat.getCantJuego(anio);
            txtVerResultadosJuegosAnio.setText(Integer.toString(reslut));
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVerJuegosPorAnioActionPerformed

    private void btnRegistroGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroGeneroActionPerformed
        String genero = txtNombreGenero.getText();
        try {
            dat.createGenero(genero);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtNombreGenero.setText(null);
        txtNombreGenero.requestFocus();
    }//GEN-LAST:event_btnRegistroGeneroActionPerformed

    private void btnBuscarCompPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompPlatActionPerformed
        try {
            CompaniaPlataforma comp = dat.encontrarCompaniaPlataforma(txtCompaniaPlataforma.getText());
            if (comp != null) {
                txtCompaniaPlataforma.setText(comp.getNombre());
                lblPlatEncontrado.setText("Compañía encontrada");
            } else {
                lblPlatEncontrado.setText("Compañía no encontrada.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarCompPlatActionPerformed

    private void btnBuscarCompEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompEnActionPerformed
        try {
            CompaniaEngine comp = dat.encontrarCompaniaEngine(txtCompaniaEngine.getText());
            
            if (comp != null) {
                txtCompaniaEngine.setText(comp.getNombre());
                lblEngineEncontrado.setText("Compañía encontrada.");
            } else {
                lblEngineEncontrado.setText("Compañía no encontrada.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarCompEnActionPerformed

    private void btnRegistrarPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPlataformaActionPerformed
        String plataforma = txtNombrePlataforma.getText();
        String comp = txtCompaniaPlataforma.getText();
        
        try {
            dat.createPlataforma(plataforma, comp);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtNombrePlataforma.setText(null);
        txtCompaniaPlataforma.setText(null);
        txtNombrePlataforma.requestFocus();
    }//GEN-LAST:event_btnRegistrarPlataformaActionPerformed

    private void btnRegistrarEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEngineActionPerformed
        String engin = txtNombreEngine.getText();
        String comp = txtCompaniaEngine.getText();
        
        try {
            dat.createEngine(engin, comp);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtNombreEngine.setText(null);
        txtCompaniaEngine.setText(null);
        txtNombreEngine.requestFocus();
    }//GEN-LAST:event_btnRegistrarEngineActionPerformed

    private void btnRegistrarStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarStaffActionPerformed
        String nombre = txtNombreStaff.getText();
        try {
            dat.createStaff(nombre);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtNombreStaff.setText(null);
        txtNombreStaff.requestFocus();
    }//GEN-LAST:event_btnRegistrarStaffActionPerformed

    private void btnAceptarRegistroJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRegistroJuegoActionPerformed
        String titulo = txtTitulo.getText();
        String genero = (String) cboGenero.getSelectedItem();
        String anio = txtAnio.getText();
        String plataforma = (String) cboPlataforma.getSelectedItem();
        String engine = (String) cboEngine.getSelectedItem();
        String unidades = (String) spnUnidades.getValue();
        String version = txtVersion.getText();
        
        
    }//GEN-LAST:event_btnAceptarRegistroJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarDespedirStaff;
    private javax.swing.JButton btnAceptarRegistroJuego;
    private javax.swing.JButton btnBuscarCompEn;
    private javax.swing.JButton btnBuscarCompPlat;
    private javax.swing.JButton btnRegistrarEngine;
    private javax.swing.JButton btnRegistrarPlataforma;
    private javax.swing.JButton btnRegistrarStaff;
    private javax.swing.JButton btnRegistroGenero;
    private javax.swing.JButton btnVerJuegosPorAnio;
    private javax.swing.JComboBox<String> cboEngine;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JComboBox<String> cboPlataforma;
    private javax.swing.JFrame frameBorrar;
    private javax.swing.JFrame frameEstadisticas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblCompaniaEngine;
    private javax.swing.JLabel lblCompaniaPlataforma;
    private javax.swing.JLabel lblDespedirStaff;
    private javax.swing.JLabel lblEngine;
    private javax.swing.JLabel lblEngineEncontrado;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblJuegosPorAnio;
    private javax.swing.JLabel lblNombreEngine;
    private javax.swing.JLabel lblNombreGenero;
    private javax.swing.JLabel lblNombrePlataforma;
    private javax.swing.JLabel lblNombreStaff;
    private javax.swing.JLabel lblPlatEncontrado;
    private javax.swing.JLabel lblPlataforma;
    private javax.swing.JLabel lblResultadosPorAnio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidadesVendidas;
    private javax.swing.JLabel lblVersionJuego;
    private javax.swing.JMenuBar mebApp;
    private javax.swing.JMenuItem meiAcercaDe;
    private javax.swing.JMenuItem meiBorrar;
    private javax.swing.JMenuItem meiEstadisticas;
    private javax.swing.JMenu menArchivo;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JPanel pnlBorrarStaff;
    private javax.swing.JPanel pnlRegistroEngine;
    private javax.swing.JPanel pnlRegistroGenero;
    private javax.swing.JPanel pnlRegistroJuego;
    private javax.swing.JPanel pnlRegistroPlataforma;
    private javax.swing.JPanel pnlRegistroStaff;
    private javax.swing.JPanel pnlVerJuegos;
    private javax.swing.JPanel pnlVerJuegosPorAnio;
    private javax.swing.JPanel pnlVerStaff;
    private javax.swing.JPanel pnlVerStaffDespedido;
    private javax.swing.JSpinner spnUnidades;
    private javax.swing.JTable tabJuegos;
    private javax.swing.JTable tabStaff;
    private javax.swing.JTable tabStaffDespedido;
    private javax.swing.JTabbedPane tbpPanel;
    private javax.swing.JTabbedPane tpEstadisticas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCompaniaEngine;
    private javax.swing.JTextField txtCompaniaPlataforma;
    private javax.swing.JTextField txtNombreEngine;
    private javax.swing.JTextField txtNombreGenero;
    private javax.swing.JTextField txtNombrePlataforma;
    private javax.swing.JTextField txtNombreStaff;
    private javax.swing.JTextField txtNombreStaffDespedido;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVerJuegosPorAnio;
    private javax.swing.JTextField txtVerResultadosJuegosAnio;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables

    public void playSound() {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\cl\\mochasoft\\res\\Unused Song 2.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Hay un error con el sonido, contacte a janjell.");
            ex.printStackTrace();
        }
    }

    private void cargarTblJuegos() {
        try {
            List<Juego> col = dat.viewJuegos();
            TMJuegos model = new TMJuegos(col);
            tabJuegos.setModel(model);
            System.out.println("Se carga tabla");
        } catch (SQLException ex) {
            System.out.println("Error:" + ex);
        }
    }

    private void cargarTblStaff() {
        try {
            List<Staff> col = dat.viewStaff();
            TMStaff model = new TMStaff(col);
            tabStaff.setModel(model);
            System.out.println("Se carga tabla");
        } catch (SQLException ex) {
            System.out.println("Error:" + ex);
        }
    }

    private void cargarTblStaffDespedido() {
        try {
            List<StaffDespedido> col = dat.viewStaffDespedido();
            TMStaffDespedido model = new TMStaffDespedido(col);
            tabStaffDespedido.setModel(model);
            System.out.println("Se carga tabla");
        } catch (SQLException ex) {
            System.out.println("Error:" + ex);
        }
    }
}
